# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!
pod 'Alamofire', '~> 3.4'
pod 'MJRefresh', '~> 3.1.0'
pod 'SDWebImage'
pod 'SnapKit'
#pod 'SKPhotoBrowser'
pod 'ALCameraViewController', '~> 1.2.0'
#pod 'QRCodeReader.swift', '~> 6.0.0'
pod 'CameraManager', '~> 2.2'
#pod 'ActiveLabel'
#pod 'RealmSwift'
pod 'FMDB'
#pod 'SDAutoLayout', '~> 2.1.1'
pod 'HYLabel'
pod 'ReachabilitySwift'
pod 'SVProgressHUD'
pod 'FDFullscreenPopGesture', '1.1'
pod 'SwiftQRCode'
pod 'ObjectMapper', '~> 1.3.0'
pod 'SwiftyJSON', '~> 2.3.2'